# helm upgrade -i turbulent-horse stable/kube2iam -f helm/kube2iam.yaml
---
extraArgs:
  base-role-arn: arn:aws:iam::064726124369:role/
#   default-role: kube2iam-default
#   api-server: ...
#   api-token: ...

host:
  ip: $(HOST_IP)
  iptables: true
  interface: cni0

image:
  repository: jtblin/kube2iam
  tag: 0.2.2
  pullPolicy: IfNotPresent

## Node labels for pod assignment
## Ref: https://kubernetes.io/docs/user-guide/node-selection/
nodeSelector:
  node-role.kubernetes.io/node: "true"

## Annotations to be added to pods
##
podAnnotations: {}

resources: {}
  # limits:
  #   cpu: 4m
  #   memory: 16Mi
  # requests:
  #   cpu: 4m
  #   memory: 16Mi

verbose: false
