# helm upgrade -i dapper-whale opsgoodness/prometheus-operator --namespace monitoring -f helm/prometheus-operator.yaml
---
global:
  ## Hyperkube image to use when getting ThirdPartyResources & cleaning up
  ##
  hyperkube:
    repository: quay.io/coreos/hyperkube
    tag: v1.5.6_coreos.0
    pullPolicy: IfNotPresent

## Prometheus-operator image
##
image:
  repository: quay.io/coreos/prometheus-operator
  tag: v0.7.0
  pullPolicy: IfNotPresent

## Node labels for prometheus-operator pod assignment
##
nodeSelector: {}

## If true, create & use RBAC resources
##
rbacEnable: false

## If true, collect & send anonymous usage statistics
## Ref: https://github.com/coreos/prometheus-operator#installation
##
sendAnalytics: true

## Prometheus-operator resource limits & requests
## Ref: https://kubernetes.io/docs/user-guide/compute-resources/
##
resources: {}
  # limits:
  #   cpu: 200m
  #   memory: 100Mi
  # requests:
  #   cpu: 100m
  #   memory: 50Mi
